// This file is auto-generated by sveltekit-translations-loader plugin
// Do not edit manually

import { getTData } from '$lib/helpers/utils.js';

/**
 * @description Nested Layout Title
 */
export const layoutTitle = (): string => {
  const data = getTData();
  return data['layoutTitle'];
};
