// This file is auto-generated by sveltekit-translations-loader plugin
// Do not edit manually

import { getTData } from 'sveltekit-translations-loader';

/**
 * @description Goodbye (default)
 */
export const goodbye = (): string => {
  const data = getTData();
  return data['goodbye'];
};
