// This file is auto-generated by sveltekit-translations-loader plugin
// Do not edit manually

import { getTData } from '$lib/helpers';

/**
 * @description Hello (default)
 */
export const hello = (): string => {
  const data = getTData();
  return data['hello'];
};
