// This file is auto-generated by sveltekit-translations-loader plugin
// Do not edit manually

import { r, getTData } from 'sveltekit-translations-loader';

/**
 * @description Hey {{name}}
 */
export const hey = (name: string | number): string => {
  const data = getTData();
  const text = data['hey'];
  return r(text, { name });
};
