// This file is auto-generated by sveltekit-translations-loader plugin
// Do not edit manually

import { getTData } from 'sveltekit-translations-loader';

/**
 * @description This is a layout description that will be inherited by child routes
 */
export const layoutDescription = (): string => {
  const data = getTData();
  return data['layoutDescription'];
};
