// This file is auto-generated by sveltekit-translations-loader plugin
// Do not edit manually

import { r, getTData } from '$lib/helpers/utils.js';

/**
 * @description Hello {{name}}, you have {{count}} messages
 */
export const nestedParams = (params?: Record<string, string | number>): string => {
  const data = getTData();
  const text = data['nested-params'];
  return r(text, params);
};
