// This file is auto-generated by sveltekit-translations-loader plugin
// Do not edit manually

import { getTData } from 'sveltekit-translations-loader';

/**
 * @description This page content demonstrates nested route translation inheritance
 */
export const pageContent = (): string => {
  const data = getTData();
  return data['pageContent'];
};
