// This file is auto-generated by sveltekit-translations-loader plugin
// Do not edit manually
import { getTData } from '$lib/helpers';

/**
 * @description Nested Page Title
 */
export const pageTitle = (): string => {
  const data = getTData();
  return data['pageTitle'];
};