// Auto-generated TypeScript declarations for @sveltekit-translations-loader
// This file is generated by the sveltekit-translations-loader plugin
// Do not edit manually

declare module '@sveltekit-translations-loader' {
	// Re-export all translation functions
	export * from './index.ts';
	
	// Namespace for t.hello() syntax
	export const t: {
		/**
		 * Hello (default)
		 */
		hello: () => string;
		/**
		 * Goodbye (default)
		 */
		goodbye: () => string;
		/**
		 * Welcome, {{name}}!
		 */
		welcome: (name: string | number | boolean) => string;
		/**
		 * There {{count}} users online
		 */
		userCount: (count: string | number | boolean) => string;
		/**
		 * Hello {{name}}, you have {{count}} messages
		 */
		nestedParams: (params?: Record<string, string | number | boolean>) => string;
		/**
		 * Hey {{name}}
		 */
		hey: (name: string | number | boolean) => string;
		/**
		 * Zap
		 */
		zap: () => string;
		/**
		 * Nested Layout Title
		 */
		layoutTitle: () => string;
		/**
		 * This is a layout description that will be inherited by child routes
		 */
		layoutDescription: () => string;
		/**
		 * Nested Page Title
		 */
		pageTitle: () => string;
		/**
		 * This page content demonstrates nested route translation inheritance
		 */
		pageContent: () => string;
	};
	
	// Individual function exports
	/**
	 * Hello (default)
	 */
	export function hello(): string;
	/**
	 * Goodbye (default)
	 */
	export function goodbye(): string;
	/**
	 * Welcome, {{name}}!
	 */
	export function welcome(name: string | number | boolean): string;
	/**
	 * There {{count}} users online
	 */
	export function userCount(count: string | number | boolean): string;
	/**
	 * Hello {{name}}, you have {{count}} messages
	 */
	export function nestedParams(params: { name: string | number | boolean; count: string | number | boolean }): string;
	/**
	 * Hey {{name}}
	 */
	export function hey(name: string | number | boolean): string;
	/**
	 * Zap
	 */
	export function zap(): string;
	/**
	 * Nested Layout Title
	 */
	export function layoutTitle(): string;
	/**
	 * This is a layout description that will be inherited by child routes
	 */
	export function layoutDescription(): string;
	/**
	 * Nested Page Title
	 */
	export function pageTitle(): string;
	/**
	 * This page content demonstrates nested route translation inheritance
	 */
	export function pageContent(): string;
}
