// This file is auto-generated by sveltekit-translations-loader plugin
// Do not edit manually
import { getTData } from '$lib/helpers';

/**
 * @description This is a test new key for file watching
 */
export const testNewKey = (): string => {
  const data = getTData();
  return data['testNewKey'];
};