// This file is auto-generated by sveltekit-translations-loader plugin
// Do not edit manually

import { r, getTData } from 'sveltekit-translations-loader';

/**
 * @description There {{count}} users online
 */
export const userCount = (count: string | number): string => {
  const data = getTData();
  const text = data['user-count'];
  return r(text, { count });
};
