// This file is auto-generated by sveltekit-translations-loader plugin
// Do not edit manually

import { r, getTData } from '$lib/helpers';

/**
 * @description Welcome, {{name}}!
 */
export const welcome = (name: string | number): string => {
  const data = getTData();
  const text = data['welcome'];
  return r(text, { name });
};
