// This file is auto-generated by sveltekit-translations-loader plugin
// Do not edit manually

import { getTData } from '$lib/helpers/utils.js';

/**
 * @description Zap
 */
export const zap = (): string => {
  const data = getTData();
  return data['zap'];
};
